# Generated by Django 3.1.5 on 2021-03-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keyboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetmfccfeature",
            name="label_type",
            field=models.CharField(
                choices=[("train", "训练数据"), ("test", "测试数据")],
                db_index=True,
                max_length=16,
                null=True,
                verbose_name="标签类型",
            ),
        ),
        migrations.AddField(
            model_name="datasetoriginaldata",
            name="label_type",
            field=models.CharField(
                choices=[("train", "训练数据"), ("test", "测试数据")],
                db_index=True,
                max_length=16,
                null=True,
                verbose_name="标签类型",
            ),
        ),
    ]
