# Generated by Django 3.1.5 on 2021-03-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keyboard", "0002_auto_20210327_1742"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlgorithmModelInst",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dataset_id", models.IntegerField(db_index=True, verbose_name="数据集ID")),
                ("algorithm", models.CharField(db_index=True, max_length=64, verbose_name="算法名称")),
                ("save_path", models.CharField(db_index=True, default="", max_length=256, verbose_name="模型存放路径")),
                ("train_info", models.JSONField(default=dict, verbose_name="训练信息")),
                ("extra_info", models.JSONField(default=dict, verbose_name="额外信息")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "算法模型实例（已训练）",
                "verbose_name_plural": "算法模型实例（已训练）",
                "ordering": ["id"],
            },
        ),
    ]
